---
sudo: required
language: python
python:
  - "3.6"
services:
  - docker

before_install:
  # Prepare Travis environment
  - sudo apt-get update
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5

  # Required packages
  - sudo apt install -y sshpass jq

  # Install Ansible
  - pip install -U pip setuptools docker
  - pip install ansible

script:
  - >
    docker run -d --security-opt label:disable
    --cap-add SYS_ADMIN
    --name node-1
    -h node-1
    irixjp/katacoda:latest /sbin/init
  - docker ps -a
  - docker exec node-1 sh -c "ps -ef"
  - docker exec node-1 sh -c "systemctl start sshd"

notifications:
  email: false
